src/account/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('registration/', views.RegistrationView.as_view(), name='registration')
]

src/gallery/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include(('show.urls', 'show'), namespace='show')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/show/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ImageDetailView.as_view(), name='detail'),
    path('add/', views.ImageCreateView.as_view(), name='add'),
    path('<int:pk>/like/', views.LikeView.as_view(), name='like'),
    path('<int:pk>/comment/', views.CommentView.as_view(), name='comment')
]

src/account/models.py
from django.db import models

# Create your models here.

src/show/models.py
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):
    photo = models.ImageField(upload_to='')
    description = models.TextField(default='')
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def user_like_it(self, user):
        return bool(Like.objects.filter(image=self, user=user))

    @property
    def url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

    @property
    def likes_count(self):
        return self.like_set.count()

    @property
    def comments_count(self):
        return self.comment_set.count()

    def __str__(self):
        return f'image: {self.description}'


class Like(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE, verbose_name='Изображение')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        unique_together = ('image', 'user')


class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE, verbose_name='Изображение')
    user = models.CharField(max_length=30, verbose_name='Автор')
    content = models.TextField(verbose_name='Комментарий')
    created_date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')

src/account/forms.py
from django.forms import ModelForm, CharField, PasswordInput
from django.contrib.auth.models import User


class UserRegistrationForm(ModelForm):
    password = CharField(label='Пароль', widget=PasswordInput)

    def save(self, commit=False):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

    class Meta:
        model = User
        fields = ('username',)

src/show/forms.py
from django.forms import ModelForm, HiddenInput
from .models import Image, Like, Comment


class ImageForm(ModelForm):

    class Meta:
        model = Image
        widgets = {'user': HiddenInput}
        fields = {'user', 'description', 'photo'}


class LikeSetForm(ModelForm):

    class Meta:
        model = Like
        fields = {'user', 'image'}


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        widgets = {'user': HiddenInput, 'image': HiddenInput}
        fields = {'content', 'user', 'image'}

src/account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserRegistrationForm
from django.contrib.auth.views import LoginView, LogoutView


class LoginUserView(LoginView):
    template_name = 'account/registration/login.html'
    next = reverse_lazy('show:index')
    redirect_authenticated_us = True
    success_url = reverse_lazy('show:index')


class RegistrationView(CreateView):

    template_name = 'account/registration/register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('account:login')


class LogoutUserView(LogoutView):
    next_page = reverse_lazy('show:index')

src/show/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic.detail import SingleObjectMixin, DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, ProcessFormView
from django.urls import reverse_lazy
from .models import Image, Like, Comment
from .forms import ImageForm, LikeSetForm, CommentForm
from .utils import ComponentsImageFormMixin


class IndexView(LoginRequiredMixin, ListView):

    template_name = 'show/index.html'
    login_url = 'account:login'
    paginate_by = 3 * 2
    model = Image

    def get_queryset(self):
        images = Image.objects.all()
        pressed_status = []
        for image in images:
            pressed_status.append(image.user_like_it(user=self.request.user))

        return list(zip(images, pressed_status))


class ImageDetailView(LoginRequiredMixin, DetailView, ComponentsImageFormMixin):
    model = Image
    template_name = 'show/detail.html'
    form_class = CommentForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        image = self.object

        context['has_like'] = image.user_like_it(user=self.request.user)
        context['page_number'] = self.request.GET.get('page', None)
        context['comments'] = Comment.objects.filter(image=self.get_object().pk)
        return context


class CommentView(LoginRequiredMixin, ProcessFormView, SingleObjectMixin, ComponentsImageFormMixin):
    model = Image
    form_class = CommentForm


class ImageCreateView(LoginRequiredMixin, CreateView):
    template_name = 'show/create.html'
    form_class = ImageForm
    success_url = reverse_lazy('show:index')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'].update({'user': self.request.user.pk, })
        return kwargs


class LikeView(LoginRequiredMixin, ProcessFormView, SingleObjectMixin, ComponentsImageFormMixin):
    model = Image
    form_class = LikeSetForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['data'] = {'user': self.request.user, 'image': self.get_object()}
        return kwargs

    def delete(self, request, *args, **kwargs):
        image = self.get_object()
        like = Like.objects.filter(user=self.request.user.id, image=image.id).first()
        if like:
            like.delete()
        return HttpResponse('OK')

src/show/templates/show/basic.html
{% load static %}

{% block javascript %}
  <script type='text/javascript' src="{% static 'show/js/ajax-script.js' %}"></script>
{% endblock %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'show/css/style.css' %}">
    <title>{% block title %}Gallery {% endblock %}</title>
  </head>
  <body>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js'></script>
    <script type='text/javascript' src="{% static 'show/js/ajax-script.js' %}"></script>

        {% if user.is_authenticated %}
            <nav>
              {{user}} | <a href="{% url 'account:logout' %}">Выход</a>
            </nav>
        {% else %}
            <nav>
              <a href="{% url 'account:login' %}"> Вход</a> |
              <a href="{% url 'account:registration' %}"> Регистрация</a>
            </nav>
        {% endif %}

  <nav>
    <a href="{% url 'show:index' %}">Главная</a>
      {% if user.is_authenticated %}
      |
        <a href="{% url 'show:add' %}">Добавить</a>
      {% endif %}
  </nav>
    <section>
    {% block content %}
    {% endblock %}
    </section>
  </body>
</html>

src/show/templates/show/create.html
{% extends "show/basic.html" %}
{% block content %}
    <div class="container">
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <br>
            <input type="submit" value = 'Добавить'>
        </form>
    </div>

{% endblock %}

src/show/templates/show/detail.html
{% extends "show/basic.html" %}

{% load static %}

{% block content %}

<div class='container'>
  <table class='tabledetail'>
    <tr><td class = 'menu user'>
      Автор: {{image.user }}|
    </td>
    <td class = 'menu'>
      Описание
    </td></tr>

    <tr><td class = 'td' width="70%">

    <figure class='gallery__item'>
      <img src='{{image.url}}'  alt='{{image.name }}' class='gallery__img'>
    </figure></td>

    <td class = 'desr'>{{image.description }}</td></tr>

    <tr><td colspan='2' class = 'menu'>
      <a href="{% url 'show:index' %}?page={{page_number}}">Назад</a> |
      <a class="imagelike {% if has_like %} pressed {% endif %}" id="like{{image.id}}" data-image_id='{{ image.id }}' href='#' >Нравится</a> |
       <div class = 'count_likes' id='count_likes_{{image.id}}'>{{image.likes_count}}</div>
  </table>

        <form method="POST" action="" id="new_comment_form">
          {% csrf_token %}
          {{form.as_p}}
        </form>
      <a class = 'imagecomment' id="button_add_comment" data-method = 'post' data-url="{% url 'show:comment' pk=image.pk %}" data-user='{{ user }}' data-image='{{ image.pk }}' href='#' >Добавить комментарий</a>

      <div id='comments'>
      {% if comments %}
        {% for comment in comments %}
          <div id='comment-{{comment.pk}}'>
          <h5>{{ comment.user }}</h5>
          <p>{{ comment.content }}</p>
          </div>
        {% endfor %}
      {% else %}
      <h5>Комментарий нет</h5>
      {% endif %}
      </div>
</div>



{% endblock %}

src/show/templates/show/index.html
{% extends "show/basic.html" %}
{% block content %}
    <div class = "page">
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        &nbsp;&nbsp; | &nbsp;&nbsp;
      {% endif %}
      {{page_obj.number}} страница
      {% if page_obj.has_next %}
      &nbsp;&nbsp; | &nbsp;&nbsp;
      <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
      {% endif %}
    </div>
    {% if object_list %}
    <div class="container">
      <div class="gallery">
        {% for image, like_press in object_list  %}
           <figure class='gallery__item' >
            <div class="card">
                  <div class="gallery__user">
                  <b>{{image.user}}</b>
                </div>
                <div class="gallery__img">
                  <a href="{% url 'show:detail' pk=image.pk %}?page={{page_obj.number}}" ><img src="{{image.url}}"  class="img"></a>
                </div>

                <div class="gallery__description">
                  <p>{{image.description }}</p>
                    <a class= "imagelike {% if like_press %} pressed {% endif %}" id="like{{image.id}}" data-image_id='{{ image.id }}' href='{{ image.id }}/' >Нравится</a> |
                  <div class = 'count_likes' id='count_likes_{{image.id}}'>{{image.likes_count}}</div>
                </div>
            </div>
           </figure>
        {% endfor %}
          </div>
    </div>
    {% else %}
  <p>No images are available.</p>
  {% endif %}
{% endblock %}